reuse makefile

diff --git a/media/toolbox/Makefile b/media/toolbox/Makefile
--- a/media/toolbox/Makefile
+++ b/media/toolbox/Makefile
@@ -2,8 +2,9 @@ ENVS := $(filter-out all,$(wildcard overlays/*))
 ENVS := $(notdir $(ENVS))
 KUSTOMIZE_CMD = kustomize build
 KUBECTL_APPLY = | kubectl apply -f -
+KUBECTL_DELETE = | kubectl delete -f -
 
-preview-%:
+plan-%:
 	@if echo "$(ENVS)" | grep -wq "$*"; then \
 		$(KUSTOMIZE_CMD) overlays/$*; \
 	else \
@@ -21,7 +22,23 @@ apply-%:
 		echo "Invalid environment: $*. Valid options are: $(ENVS)"; exit 1; \
 	fi
 
+delete-%:
+	@if [ "$*" = "all" ]; then \
+		for env in $(ENVS); do \
+			$(KUSTOMIZE_CMD) overlays/$$env $(DELETE); \
+		done; \
+	elif echo "$(ENVS)" | grep -wq "$*"; then \
+		$(KUSTOMIZE_CMD) overlays/$* $(DELETE); \
+	else \
+		echo "Invalid environment: $*. Valid options are: $(ENVS)"; exit 1; \
+	fi
+
 apply-all:
 	@for env in $(ENVS); do \
 		$(MAKE) apply-$$env; \
+	done
+
+delete-all:
+	@for env in $(ENVS); do \
+		$(MAKE) delete-$$env; \
 	done
